export interface ValuationIndex {
    id: number
    institution_id: string
    institution_template_id: string
    initiation_date: date
    branch_name: string
    application_number: string
    application_number_2: string
    received_from: string
    branch_contact_person_name: string
    branch_contact_person_phone_number: string
    branch_contact_person_alternate_phone_number: string
    owner_name: string
    case_type: string
    earlier_valuation_done: string
    earlier_valuer_name: string
    earlier_valuation_date: string
    expected_completion_date: date
    reference_number: string
    title: string
    address: string
    applicant_name: string
    applicant_phone_number: string
    applicant_alternate_phone_number: string
    applicant_email: string
    applicant_alternate_email: string
    same_as_applicant: string
    contact_name: string
    contact_phone_number: string
    contact_alternate_phone_number: string
    contact_email: string
    contact_alternate_email: string
    fee: string
    dispatch_date: string
    formatted_dispatch_date: string
    inward_remarks: string
    visitor_name: string
    maker_user_id: number
    area_location: string
    dispatch_date: date
    property_id: number
    property_visit_id: number
    status_code: string
    status_desc: string
    draft: boolean
    in_progress: boolean
    ready_for_visit: boolean
    ready_for_visit_or_delayed: boolean
    visited: boolean
    visit_completed: boolean
    valuation_completed: boolean
    valuation_cancelled: boolean
    cancellable: boolean
    display_ready_to_visit: boolean
    proposed_visitor: number
    formatted_visit_rescheduled_date: string
    visit_delay_reason: string
}